
// Country codes to names mapping
const countries: Record<string, string> = {
  "af": "Afganistán",
  "al": "Albania",
  "de": "Alemania",
  "ad": "Andorra",
  "ao": "Angola",
  "ai": "Anguila",
  "aq": "Antártida",
  "ag": "Antigua y Barbuda",
  "sa": "Arabia Saudita",
  "dz": "Argelia",
  "ar": "Argentina",
  "am": "Armenia",
  "aw": "Aruba",
  "au": "Australia",
  "at": "Austria",
  "az": "Azerbaiyán",
  "bs": "Bahamas",
  "bd": "Bangladés",
  "bb": "Barbados",
  "bh": "Baréin",
  "be": "Bélgica",
  "bz": "Belice",
  "bj": "Benín",
  "bm": "Bermudas",
  "by": "Bielorrusia",
  "bo": "Bolivia",
  "ba": "Bosnia y Herzegovina",
  "bw": "Botsuana",
  "br": "Brasil",
  "bn": "Brunéi",
  "bg": "Bulgaria",
  "bf": "Burkina Faso",
  "bi": "Burundi",
  "bt": "Bután",
  "cv": "Cabo Verde",
  "kh": "Camboya",
  "cm": "Camerún",
  "ca": "Canadá",
  "td": "Chad",
  "cl": "Chile",
  "cn": "China",
  "cy": "Chipre",
  "co": "Colombia",
  "km": "Comoras",
  "cg": "Congo",
  "kp": "Corea del Norte",
  "kr": "Corea del Sur",
  "cr": "Costa Rica",
  "ci": "Costa de Marfil",
  "hr": "Croacia",
  "cu": "Cuba",
  "cw": "Curazao",
  "dk": "Dinamarca",
  "dm": "Dominica",
  "ec": "Ecuador",
  "eg": "Egipto",
  "sv": "El Salvador",
  "ae": "Emiratos Árabes Unidos",
  "er": "Eritrea",
  "sk": "Eslovaquia",
  "si": "Eslovenia",
  "es": "España",
  "us": "Estados Unidos",
  "ee": "Estonia",
  "et": "Etiopía",
  "ph": "Filipinas",
  "fi": "Finlandia",
  "fj": "Fiyi",
  "fr": "Francia",
  "ga": "Gabón",
  "gm": "Gambia",
  "ge": "Georgia",
  "gh": "Ghana",
  "gi": "Gibraltar",
  "gd": "Granada",
  "gr": "Grecia",
  "gl": "Groenlandia",
  "gp": "Guadalupe",
  "gu": "Guam",
  "gt": "Guatemala",
  "gf": "Guayana Francesa",
  "gg": "Guernsey",
  "gn": "Guinea",
  "gq": "Guinea Ecuatorial",
  "gw": "Guinea-Bisáu",
  "gy": "Guyana",
  "ht": "Haití",
  "hn": "Honduras",
  "hk": "Hong Kong",
  "hu": "Hungría",
  "in": "India",
  "id": "Indonesia",
  "iq": "Irak",
  "ir": "Irán",
  "ie": "Irlanda",
  "bv": "Isla Bouvet",
  "im": "Isla de Man",
  "cx": "Isla de Navidad",
  "nf": "Isla Norfolk",
  "is": "Islandia",
  "ky": "Islas Caimán",
  "cc": "Islas Cocos",
  "ck": "Islas Cook",
  "fo": "Islas Feroe",
  "gs": "Islas Georgias del Sur y Sandwich del Sur",
  "fk": "Islas Malvinas",
  "mp": "Islas Marianas del Norte",
  "mh": "Islas Marshall",
  "pn": "Islas Pitcairn",
  "sb": "Islas Salomón",
  "tc": "Islas Turcas y Caicos",
  "vg": "Islas Vírgenes Británicas",
  "vi": "Islas Vírgenes de los Estados Unidos",
  "il": "Israel",
  "it": "Italia",
  "jm": "Jamaica",
  "jp": "Japón",
  "je": "Jersey",
  "jo": "Jordania",
  "kz": "Kazajistán",
  "ke": "Kenia",
  "kg": "Kirguistán",
  "ki": "Kiribati",
  "kw": "Kuwait",
  "la": "Laos",
  "ls": "Lesoto",
  "lv": "Letonia",
  "lb": "Líbano",
  "lr": "Liberia",
  "ly": "Libia",
  "li": "Liechtenstein",
  "lt": "Lituania",
  "lu": "Luxemburgo",
  "mo": "Macao",
  "mk": "Macedonia del Norte",
  "mg": "Madagascar",
  "my": "Malasia",
  "mw": "Malaui",
  "mv": "Maldivas",
  "ml": "Malí",
  "mt": "Malta",
  "ma": "Marruecos",
  "mq": "Martinica",
  "mu": "Mauricio",
  "mr": "Mauritania",
  "yt": "Mayotte",
  "mx": "México",
  "fm": "Micronesia",
  "md": "Moldavia",
  "mc": "Mónaco",
  "mn": "Mongolia",
  "me": "Montenegro",
  "ms": "Montserrat",
  "mz": "Mozambique",
  "mm": "Myanmar",
  "na": "Namibia",
  "nr": "Nauru",
  "np": "Nepal",
  "ni": "Nicaragua",
  "ne": "Níger",
  "ng": "Nigeria",
  "nu": "Niue",
  "no": "Noruega",
  "nc": "Nueva Caledonia",
  "nz": "Nueva Zelanda",
  "om": "Omán",
  "nl": "Países Bajos",
  "pk": "Pakistán",
  "pw": "Palaos",
  "pa": "Panamá",
  "pg": "Papúa Nueva Guinea",
  "py": "Paraguay",
  "pe": "Perú",
  "pf": "Polinesia Francesa",
  "pl": "Polonia",
  "pt": "Portugal",
  "pr": "Puerto Rico",
  "qa": "Qatar",
  "gb": "Reino Unido",
  "cf": "República Centroafricana",
  "cz": "República Checa",
  "cd": "República Democrática del Congo",
  "do": "República Dominicana",
  "re": "Reunión",
  "rw": "Ruanda",
  "ro": "Rumanía",
  "ru": "Rusia",
  "eh": "Sahara Occidental",
  "ws": "Samoa",
  "as": "Samoa Americana",
  "bl": "San Bartolomé",
  "kn": "San Cristóbal y Nieves",
  "sm": "San Marino",
  "mf": "San Martín",
  "pm": "San Pedro y Miquelón",
  "vc": "San Vicente y las Granadinas",
  "sh": "Santa Elena, Ascensión y Tristán de Acuña",
  "lc": "Santa Lucía",
  "st": "Santo Tomé y Príncipe",
  "sn": "Senegal",
  "rs": "Serbia",
  "sc": "Seychelles",
  "sl": "Sierra Leona",
  "sg": "Singapur",
  "sx": "Sint Maarten",
  "sy": "Siria",
  "so": "Somalia",
  "lk": "Sri Lanka",
  "sz": "Suazilandia",
  "za": "Sudáfrica",
  "sd": "Sudán",
  "ss": "Sudán del Sur",
  "se": "Suecia",
  "ch": "Suiza",
  "sr": "Surinam",
  "sj": "Svalbard y Jan Mayen",
  "th": "Tailandia",
  "tw": "Taiwán",
  "tz": "Tanzania",
  "tj": "Tayikistán",
  "io": "Territorio Británico del Océano Índico",
  "tf": "Tierras Australes y Antárticas Francesas",
  "tl": "Timor Oriental",
  "tg": "Togo",
  "tk": "Tokelau",
  "to": "Tonga",
  "tt": "Trinidad y Tobago",
  "tn": "Túnez",
  "tm": "Turkmenistán",
  "tr": "Turquía",
  "tv": "Tuvalu",
  "ua": "Ucrania",
  "ug": "Uganda",
  "uy": "Uruguay",
  "uz": "Uzbekistán",
  "vu": "Vanuatu",
  "va": "Ciudad del Vaticano",
  "ve": "Venezuela",
  "vn": "Vietnam",
  "wf": "Wallis y Futuna",
  "ye": "Yemen",
  "dj": "Yibuti",
  "zm": "Zambia",
  "zw": "Zimbabue"
};

/**
 * Gets the localized country name from a country code
 * @param countryCode ISO 3166-1 alpha-2 country code
 * @returns Localized country name in Spanish or the original code if not found
 */
export const getCountryName = (countryCode: string): string => {
  return countries[countryCode.toLowerCase()] || countryCode;
};
