
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovvwxqiccfvsjjbnxgmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92dnd4cWljY2Z2c2pqYm54Z21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTE2OTAsImV4cCI6MjA2MDgyNzY5MH0.MXtvu00C6hdppjCjr6XhLTHlHTDI17cye5zsHjsUIos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
